# This is the network config written by 'subiquity'
network:
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: true
      routes:
       - to: default
         via: 192.168.1.1
      nameservers:
          addresses: [195.148.216.40, 195.148.216.39]
  version: 2
